name: discord-selfbot
services:
- name: discord-selfbot
  github:
    repo: YOUR_USERNAME/discord-selfbot
    branch: master
  run_command: python main.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: DISCORD_TOKEN
    value: YOUR_DISCORD_TOKEN_HERE
    scope: RUN_TIME
    type: SECRET
  - key: DISCORD_PREFIX
    value: "*"
    scope: RUN_TIME
  - key: DISCORD_SELENIUM_HEADLESS
    value: "true"
    scope: RUN_TIME
  - key: DISCORD_SELENIUM_IMPLICIT_WAIT
    value: "10"
    scope: RUN_TIME
  - key: DISCORD_SELENIUM_PAGE_LOAD_TIMEOUT
    value: "30"
    scope: RUN_TIME
  - key: HEALTH_CHECK_PORT
    value: "8080"
    scope: RUN_TIME

